# Generated by Django 6.1.1 on 2026-09-19 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_name',
            field=models.CharField(default='Razorpay', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(blank=True, help_text='Order ID returned by the payment gateway.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Transaction ID after successful payment.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_id',
            field=models.CharField(blank=True, help_text='Refund ID if payment was refunded.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='consultation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='consultations.consultation'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
