# Generated by Django 6.1.1 on 2026-09-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('payment_pending', 'Payment Pending'), ('paid', 'Paid (Scheduled)'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='payment_pending', max_length=20),
        ),
    ]
